#=============
# Change port beacause of Portainer !!!
dev_addr: 127.0.0.1:8001
#=============

site_name: Krzysztof Zakrzewski Portfolio
site_author: Krzysztof Zakrzewski
site_description: >-
    Portfolio projektów Krzysztofa Zakrzewskiego z Data Science i AI!

repo_name: KrzysztofZakrzewsk/portfolio
repo_url: https://github.com/KrzysztofZakrzewski/portfolio

theme:
  name: material
  palette:
    primary: brown
    accent: deep orange
  
  logo: assets/logo.png

nav:
- Home: index.md
- Data Analys:
# - Projekty ukończone:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md
  - "The 500 richest businessmen in the world": rich_500/index.md
  - "Coffee": coffee/index.md
  - "Job_offer_from_JustJoinIT": Job_offer_from_JustJoinIT/index.md
  # - "aaa": aaa/index.md
  # - "Titanic": titanic/index.md
- Projects in progress:
  - "In progrs": W_przygotowaniau/index.md
- Applications:
  - "Type Machine": "typemachine/index.md"
  - "M_Cal": "M_Cal/index.md"
  - "rich_500_app": "rich_500_app/index.md"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - styles/extra.css